{{- if and (eq .Values.deployment.hpa.enabled true) (ge .Capabilities.KubeVersion.Minor "21") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "go.application.name" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.deployment.hpa.maxReplicas }}
  minReplicas: {{ .Values.deployment.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "go.application.name" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment.hpa.targetCPU }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Value
          averageValue: {{ include "go.deployment.hpa.targetMemory" . }}
{{- end }}
