{{- if and (eq .Values.job.enabled true) .Values.job.serviceAccount.create }}
{{- $jobAnnotations := .Values.job.annotations | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go.job.serviceAccountName" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
    {{- if hasKey $jobAnnotations "helm.sh/hook" }}
    helm.sh/hook: {{ index $jobAnnotations "helm.sh/hook" | quote }}
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    {{- end }}
{{- end }}
