{{ if eq .Values.job.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
        {{- if eq .Values.job.vault.enabled true }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role }}
        vault.hashicorp.com/agent-inject-secret-env: {{ .Values.vault.env }}
        vault.hashicorp.com/agent-inject-template-env: |
            {{- if .Values.vault.sharedEnv }}
            {{`{{ with secret "` }}{{ .Values.vault.sharedEnv }}{{`"  -}}
            {{ range $k, $v := .Data.data -}}
            export {{ $k }}='{{ $v }}'
            {{ end -}}
            {{ end -}}`}}
            {{- end }}
            {{`{{ with secret "` }}{{ .Values.vault.env }}{{`"  -}}
            {{ range $k, $v := .Data.data -}}
            export {{ $k }}='{{ $v }}'
            {{ end -}}
            {{ end -}}`}}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "go.job.serviceAccountName" . }}
      containers:
        - name: {{ include "go.application.name" . }}
          image: {{ include "go.application.imageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          {{- with .Values.job.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "go.application.env" . | nindent 12 }}
          securityContext:
            runAsUser: {{ .Values.application.securityContext.runAsUser }}
            runAsGroup: {{ .Values.application.securityContext.runAsGroup }}
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
      restartPolicy: {{ .Values.job.restartPolicy }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
