{{- if eq .Values.pdb.enabled true }}
{{- if and .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
{{- fail "pdb.minAvailable and pdb.maxUnavailable cannot both be set" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "go.application.name" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable | default 2 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
