{{- if eq .Values.service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go.application.name" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
    ingress.kubernetes.io/service-upstream: "true"
    {{- if eq .Values.service.externalDNS.enabled true }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.externalDNS.host }}
    {{- end }}
    {{- if eq .Values.service.kong.stripPath "true" }}
    konghq.com/strip-path: "true"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ ternary "grpc" "http" .Values.deployment.grpc }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 50051
  selector:
    app.kubernetes.io/name: {{ include "go.application.name" . }}
{{- end }}
