{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go.application.name" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
    {{-  if .Values.aws.iamRolePrefix }}
    eks.amazonaws.com/role-arn: "{{ .Values.aws.iamRolePrefix }}{{ .Values.aws.iamRole | default (include "go.application.name" .) }}"
    {{- end -}}
{{- end }}
