{{- if and (eq .Values.virtualService.enabled true) (ne .Values.application.name "horizon") }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "go.application.name" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    {{- include "go.annotations" . | nindent 4 }}
spec:
  hosts:
    - {{ include "go.application.name" . }}
    {{- if .Values.virtualService.hosts }}
    {{- range .Values.virtualService.hosts }}
    {{ printf "- %s" .}}
    {{- end }}
    {{- end }}
  {{- if .Values.virtualService.gateways }}
  gateways:
  {{- range .Values.virtualService.gateways }}
    {{ printf "- %s" .}}
  {{- end }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ include "go.application.name" . }}
        retries:
          attempts: {{ .Values.istio.retries.attempts }}
          perTryTimeout: {{ .Values.istio.retries.perTryTimeout }}
{{- end }}
