{{ if eq .Values.supervisor.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-configmap
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
data:
  supervisord.conf: |-
    [supervisord]
    nodaemon=true
    logfile=/dev/stdout
    logfile_maxbytes=0
    pidfile=/var/run/supervisord.pid
    loglevel = INFO
    environment=USER="www-data"

    [program:php-fpm]
    command = /usr/local/sbin/php-fpm
    directory = /var/www/html
    autostart=true
    autorestart=true
    priority=5
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    {{ if eq .Values.supervisor.horizon.enabled true }}

    [program:horizon]
    command = php artisan horizon
    directory = /var/www/html
    autostart=true
    autorestart=true
    priority=2
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    {{ else }}

    [program:queue-work]
    command = php artisan queue:work
    directory = /var/www/html
    autostart=true
    autorestart=true
    priority=2
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    stderr_logfile=/dev/stderr
    stderr_logfile_maxbytes=0

    {{ end }}

  {{ end }}
