{{/* Horizon has its own bespoke nginx configuration. Please refer to horizon repository */}}
{{ if ne .Values.application.name "horizon" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
data:
  default.conf: |-
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    server_tokens off;
    client_max_body_size {{ .Values.nginx.config.clientMaxBodySize }};
    server {
      listen 8080 default_server;
      listen [::]:8080 default_server;
      root /var/www/html/public;
      server_name _;
      index index.php;
      if ($request_method !~ ^(GET|POST|PATCH|DELETE)$ ) {
          return 405;
      }
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-XSS-Protection "1; mode=block";
      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }
      location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
      }
    }
  {{- end }}
