{{- if eq .Values.application.name "data-feed" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php.application.name" . }}-queue
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "php.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- include "php.annotations" . | nindent 8 }}
        {{- include "php.application.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "php.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "php.application.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if eq (include "php.cloud.provider" .) "Azure" }}
        {{- if eq .Values.azure.identity.enabled true }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "php.application.name" . }}
      containers:
        - name: {{ include "php.application.name" . }}
          image: {{ include "php.application.imageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          args: [ "queue" ]
          securityContext: {{ include "node.application.securityContext" . | nindent 12 }}
          env:
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- range .Values.application.env }}
            - name: "{{.name}}"
              value: "{{.value}}"
            {{- end}}
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          volumeMounts:
            - name: fpm-pool-config-volume
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: php-config-volume
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: shared-files
              mountPath: /var/www/html
            - name: tmp
              mountPath: /tmp
            - name: newrelic-log
              mountPath: /var/log/newrelic/

      securityContext:
        fsGroup: 1000

      volumes:
        - name: fpm-pool-config-volume
          configMap:
            name: fpm-pool-configmap
        - name: php-config-volume
          configMap:
            name: php-configmap
        - name: shared-files
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: newrelic-log
          emptyDir: {}
{{- end }}
