{{- if eq .Values.application.name "horizon" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "microservice.application.name" . }}
spec:
  hosts:
    - {{ include "microservice.application.name" . }}

  http:
    - name: oldworld-header
      match:
        - headers:
            x-world:
              exact: "oldworld"
      route:
        - destination:
            host: {{ include "microservice.application.name" . }}
            subset: oldworld
          headers:
            request:
              set:
                X-Forwarded-Proto: "https"
      retries:
        attempts: 1
        perTryTimeout: 10s
    - name: default-behavior
      route:
        - destination:
            host: {{ include "microservice.application.name" . }}
            subset: newworld
          headers:
            request:
              set:
                X-Forwarded-Proto: "https"
      retries:
        attempts: 1
        perTryTimeout: 10s
{{- end }}