name: 🐛 Bug report
description: Create a bug report to help us improve!
title: "[BUG]: <title>"
labels: [bug, triage]
body:        
  - type: checkboxes
    attributes:
      label: Is there an existing issue raised for this?
      description: Please search to see if an issue already exists for the bug you've encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: input
    attributes:
      label: Chart version?
      description: Enter the version of the chart.
      placeholder: v0.0.15
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current behaviour
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A concise description of what you expect to happen.
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A concise description of the steps needed to reproduce the issue. Please include all `helm` commands you are running.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else we need to know?
      placeholder: This is affecting service `foo` on environment `bar`
    validations:
      required: false
