name: 📖 Documentation request
description: Suggest an idea to improve our documentation.
title: "[DOC]: <title>"
labels: [documentation]
body:
- type: dropdown
  attributes:
    label: Documentation improvement or addition?
    multiple: false
    options:
      - Improvement
      - Addition
  validations:
    required: true

- type: textarea
  attributes:
    label: What would you like documented?
    description: A clear and concise description of what you want to be documented.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context.
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
