name: ✨ Feature request
description: Suggest an feature for one of the charts!
title: "[FEATURE]: <title>"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing feature request raised for this?
    description: Please search to see if feature request already exists for the feature you'd like.
    options:
    - label: I have searched the existing feature requests
      required: true

- type: textarea
  attributes:
    label: What limitations is this causing?
    description: Give a clear and concise description of what the problem is.
    placeholder:  I'm always frustrated when [...] or It would be nice to have the ability to [...]
  validations:
    required: true

- type: textarea
  attributes:
    label: Desired behaviour
    description: A clear and concise description of what you want to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe any possible solutions you've considered.
    description: A clear and concise description of any alternative solutions or features you've considered. If nothing, please enter `NONE`
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context.
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
