{{- if and (eq .Values.ingress.enabled true) (ge .Capabilities.KubeVersion.Minor "21") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "php.application.name" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
    konghq.com/strip-path: "true"
    konghq.com/override: do-not-preserve-host
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "php.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- if .Values.ingress.pathRouted }}
          - path: {{ .Values.ingress.pathRouted }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "php.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          {{- if .Values.ingress.pathMasked }}
          - path: {{ .Values.ingress.pathMasked }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "php.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
{{- end }}
