{{ if eq .Values.job.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 12 }}
spec:
  template:
    metadata:
      annotations:
        {{- if eq .Values.job.vault.enabled true }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role }}
        vault.hashicorp.com/agent-inject-secret-env: {{ .Values.vault.env }}
        vault.hashicorp.com/agent-inject-template-env: |
            {{`{{ with secret "` }}{{ .Values.vault.env }}{{`"  -}}
            {{ range $k, $v := .Data.data -}}
            export {{ $k }}='{{ $v }}'
            {{ end -}}
            {{ end -}}`}}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "php.application.name" . }}
      containers:
        - name: {{ include "php.application.name" . }}
          image: {{ include "php.application.imageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          args: ["{{ .Values.cron.args }}"]
          securityContext: {{ include "node.application.securityContext" . | nindent 12 }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          {{- if .Values.newrelic.ephemeralPods.enabled }}
          volumeMounts:
            - name: newrelic-log
              mountPath: /var/log/newrelic/
          {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- if .Values.newrelic.ephemeralPods.enabled }}
      volumes:
        - name: newrelic-log
          emptyDir: {}
      {{- end }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
