{{- if eq .Values.peerAuthentication.enabled true }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "php.application.name" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
