{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "php.application.name" . }}
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
    {{-  if .Values.aws.iam.enabled }}
    eks.amazonaws.com/role-arn: "{{ .Values.aws.iam.rolePrefix }}{{ .Values.aws.iam.role | default (include "php.application.name" .) }}"
    {{- end -}}
{{- end }}
