{{- if eq (include "node.cloud.provider" .) "Azure" }}
{{- if eq .Values.azure.identity.enabled true }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: "{{ .Values.azure.identity.idName }}"
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
spec:
  type: 0
  resourceID: "{{ .Values.azure.identity.resourceName }}"
  clientID: "{{ .Values.azure.identity.clientName }}"
{{- end }}
{{- end }}
