{{- if eq .Values.deployment.enabled true}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node.application.name" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "node.application.name" . }}"
  template:
    metadata:
      annotations:
        {{- include "node.annotations" . | nindent 8 }}
        {{- include "node.application.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "node.labels" . | nindent 8 }}
        {{- if and (eq (include "node.cloud.provider" .) "Azure") (eq .Values.azure.identity.enabled true) }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- include "node.deployment.topologySpreadConstraints" . | nindent 6 }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "node.application.name" .) }}
      containers:
        - name: "{{ include "node.application.name" . }}"
          image: {{ .Values.application.image.tag }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          env:
            - name: APP_NAME
              value: {{ .Values.application.name | lower | quote }}
            - name: DISABLE_INSTANA
              value: "TRUE"
            - name: PLATFORM
              value: "{{ include "node.cloud.provider" . }}"
            {{- if eq (include "node.cloud.provider" .) "AWS" }}
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- end }}
            {{- range .Values.application.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.application.ports.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          livenessProbe:
            {{- if eq .Values.application.livenessProbe.type "tcp" }}
            tcpSocket:
              port: {{ .Values.application.livenessProbe.port  }}
            {{- else }}
            httpGet:
              port: 3000
              path: {{ .Values.application.readinessProbe.path }}
            {{- end }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            {{- if eq .Values.application.readinessProbe.type "tcp" }}
            tcpSocket:
              port: {{ .Values.application.readinessProbe.port  }}
            {{- else }}
            httpGet:
              port: 3000
              path: {{ .Values.application.readinessProbe.path }}
            {{- end }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if .Values.application.extraVolumes -}}
            {{- include "node.application.extraConfigmapMounts" . | nindent 12 }}
            {{- end }}
      securityContext:
        fsGroup: 1000
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if .Values.application.extraVolumes -}}
        {{- include "node.application.extraConfigmapVolumes" . | nindent 8 }}
        {{- end }}
{{- end }}
