{{- if eq .Values.supervisor.enabled true -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node.application.name" . }}-supervisor
  labels:
    app.kubernetes.io/name: {{ include "node.application.name" . }}-supervisor
    chart: {{ include "node.chartref" . }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node.application.name" . }}-supervisor
  template:
    metadata:
      annotations:
        {{- include "node.annotations" . | nindent 8 }}
        {{- include "node.application.vault.annotations" . | nindent 8 }}
      labels:
        app.kubernetes.io/name: {{ include "node.application.name" . }}-supervisor
        chart: {{ include "node.chartref" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "node.application.name" . }}
      containers:
        - name: {{ include "node.application.name" . }}-supervisor
          image: "{{ include "node.application.imageURL" . }}"
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          args: ["supervisor"]
          securityContext: {{ include "node.application.securityContext" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - pgrep -a supervisord
          env:
            - name: PLATFORM
              value: "{{ include "node.cloud.provider" . }}"
            - name: APP_NAME
              value: {{ .Values.application.name | lower | quote }}
            {{- if eq (include "node.cloud.provider" .) "AWS" }}
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- end }}
            {{- range .Values.application.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - name: supervisor-config-volume
              mountPath: /etc/supervisord.conf
              subPath: supervisord.conf
            - name: tmp
              mountPath: /tmp
            {{- if .Values.application.extraVolumes -}}
            {{- include "node.application.extraConfigmapMounts" . | nindent 12 }}
            {{- end }}
      securityContext:
        fsGroup: 1000
      volumes:
        - name: supervisor-config-volume
          configMap:
            name: supervisor-configmap
        - name: tmp
          emptyDir: {}
        {{- if .Values.application.extraVolumes -}}
        {{- include "node.application.extraConfigmapVolumes" . | nindent 8 }}
        {{- end }}
{{- end -}}
