{{ if eq .Values.job.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  annotations:
    {{- toYaml .Values.job.annotations | nindent 12 }}
spec:
  template:
    metadata:
      annotations:
        {{- include "node.istio.proxy.annotations" . | nindent 8 }}
        {{- if eq .Values.job.vault.enabled true }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: {{ .Values.vault.role }}
        vault.hashicorp.com/agent-inject-secret-env: {{ .Values.vault.env }}
        vault.hashicorp.com/agent-inject-template-env: |
            {{- if .Values.vault.sharedEnv }}
            {{`{{ with secret "` }}{{ .Values.vault.sharedEnv }}{{`"  -}}
            {{ range $k, $v := .Data.data -}}
            export {{ $k }}='{{ $v }}'
            {{ end -}}
            {{ end -}}`}}
            {{- end }}
            {{`{{ with secret "` }}{{ .Values.vault.env }}{{`"  -}}
            {{ range $k, $v := .Data.data -}}
            export {{ $k }}='{{ $v }}'
            {{ end -}}
            {{ end -}}`}}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ include "node.application.name" . }}
      containers:
        - name: {{ include "node.application.name" . }}
          image: {{ include "node.application.imageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          securityContext: {{ include "node.application.securityContext" . | nindent 12 }}
          env:
            {{- $defaults := list
                (dict "name" "APP_NAME" "value" (.Values.application.name | lower))
                (dict "name" "DISABLE_INSTANA" "value" "true")
                (dict "name" "PLATFORM" "value" (include "node.cloud.provider" .))
                (dict "name" "SENTRY_ENABLED" "value" "true")
                (dict "name" "SENTRY_ENVIRONMENT" "value" .Values.cloud.environment)
                (dict "name" "SENTRY_PROFILING_TRACE_SAMPLE_RATE" "value" (ternary "0.5" "1" (any (eq .Values.cloud.environment "demo") (eq .Values.cloud.environment "production"))))
                (dict "name" "SENTRY_PROFILING_PROFILES_SAMPLE_RATE" "value" "1") }}
            {{- if eq (include "node.cloud.provider" .) "AWS" }}
            {{- $defaults = append $defaults (dict "name" "AWS_REGION" "value" .Values.cloud.region) }}
            {{- end }}
            {{- $defaults = append $defaults (dict "name" "NODE_OPTIONS" "value" (printf "--max-http-header-size=%v%s" (.Values.application.nodeOptions.maxHttpHeaderSize | default 65536) (ternary (printf " --max-old-space-size=%v" .Values.application.nodeOptions.maxOldSpaceSize) "" (not (empty .Values.application.nodeOptions.maxOldSpaceSize))))) }}
            {{- include "node.application.env" (dict "defaults" $defaults "env" .Values.application.env) | nindent 12 }}
          resources:
            {{- include "node.resources" .Values.job.resources | nindent 12 }}
      restartPolicy: {{ .Values.job.restartPolicy }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  {{- end }}
