{{ if eq .Values.application.migrations.enabled true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "node.application.name" . }}-migrations"
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      annotations:
        {{- include "node.annotations" . | nindent 8 }}
        {{- include "node.application.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "node.labels" . | nindent 8 }}
        {{- if and (eq (include "node.cloud.provider" .) "Azure") (eq .Values.azure.identity.enabled true) }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "node.application.name" .) }}
      containers:
        - name: "{{ include "node.application.name" . }}"
          image: "{{ include "node.application.imageURL" . }}"
          args: ["{{.Values.application.migrations.args }}"]
          env:
            - name: APP_NAME
              value: {{ include "node.application.name" . | quote }}
            - name: DISABLE_INSTANA
              value: "TRUE"
            - name: PLATFORM
              value: "{{ include "node.cloud.provider" . }}"
             {{- if eq (include "node.cloud.provider" .) "AWS" }}
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
             {{- end }}
             {{- range .Values.application.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
             {{- end }}
          securityContext:
            runAsUser: 1000 # User "app" within the container
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
      restartPolicy: {{ .Values.application.migrations.restartPolicy }}
  backoffLimit: {{ .Values.application.migrations.backoffLimit }}
  {{- end }}
