{{- if eq .Values.serviceAccount.enabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "node.application.name" .) }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
    {{-  if .Values.aws.iamRolePrefix }}
    eks.amazonaws.com/role-arn: "{{ .Values.aws.iamRolePrefix }}{{ include "node.application.name" . }}"
    {{- end -}}
{{- end }}
