{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "node.application.name" .) }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    {{- include "node.annotations" . | nindent 4 }}
    {{-  if .Values.aws.iam.enabled }}
    eks.amazonaws.com/role-arn: "{{ .Values.aws.iamRolePrefix }}{{ .Values.aws.iamRole | default (include "node.application.name" .) }}"
    {{- end -}}
{{- end }}
