{{- if and (eq .Values.application.name "horizon") (eq .Values.application.cron.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "php.application.name" . }}-cron
  labels:
    {{- include "php.labels" . | nindent 4 }}
    version: cron
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "php.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: cron
  template:
    metadata:
      annotations:
        {{- include "php.annotations" . | nindent 8 }}
        {{- include "php.application.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "php.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "php.application.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if eq (include "php.cloud.provider" .) "Azure" }}
        {{- if eq .Values.azure.identity.enabled true }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        {{- end }}
        version: cron
    spec:
      serviceAccountName: {{ include "php.application.name" . }}
      containers:
        - name: "{{ include "php.application.name" . }}"
          image: "{{ include "php.application.imageURL" . }}"
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          args: [ "true" ]
          securityContext: {{ include "node.application.securityContext" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - pgrep -a php
          env:
            - name: PLATFORM
              value: {{ include "php.cloud.provider" . }}
            - name: APP_NAME
              value: "{{ include "php.application.name" . }}-cron"
            {{- if eq (include "php.cloud.provider" .) "AWS" }}
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- end }}
            - name: CRON
              value: "true"
            - name: CONTAINER
              value: "true"
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
            requests:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: php-config-volume
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: shared-files
              mountPath: /var/www/html
            - name: tmp
              mountPath: /tmp

      securityContext:
        fsGroup: 1000

      volumes:
        - name: php-config-volume
          configMap:
            name: php-configmap-cron
        - name: shared-files
          emptyDir: {}
        - name: tmp
          emptyDir: {}
{{- end }}
