{{- if and (eq .Values.application.name "event") (ge .Capabilities.KubeVersion.Minor "21") (eq .Values.application.oldWorld.enabled true) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "php.application.name" . }}-oldworld
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
    konghq.com/strip-path: "true"
    configuration.konghq.com: do-not-preserve-host-oldworld
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.istio.externalIngress.path }}-oldworld
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "php.application.name" . }}-oldworld
                port:
                  number: {{ .Values.service.port }}
          - path: {{ .Values.istio.externalIngress.path }}-oldworld
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "php.application.name" . }}-oldworld
                port:
                  number: {{ .Values.service.port }}
{{- end }}
