{{- if and (eq .Values.application.name "event") (eq .Values.application.oldWorld.enabled true) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "php.application.name" . }}-oldworld
  labels:
    {{- include "php.labels" . | nindent 4 }}
  annotations:
    {{- include "php.annotations" . | nindent 4 }}
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "php.application.name" . }}
{{- end }}
