{{- if and (eq .Values.application.name "event") (eq .Values.application.oldWorld.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.application.name" . }}-oldworld
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
    version: oldworld
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microservice.application.name" . }}-oldworld
      app.kubernetes.io/instance: {{ .Release.Name }}-oldworld
  template:
    metadata:
      annotations:
        {{- include "microservice.annotations" . | nindent 8 }}
        {{- include "microservice.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "microservice.labels" . | nindent 8 }}
        version: oldworld
        app.kubernetes.io/name: {{ include "microservice.application.name" . }}-oldworld
        app.kubernetes.io/instance: {{ .Release.Name }}-oldworld
        {{- if eq (include "microservice.cloud.provider" .) "Azure" }}
        {{- if eq .Values.azure.identity.enabled true }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.application.name" . }}
      containers:
        - name: {{ include "microservice.application.name" . }}-oldworld
          image: {{ include "microservice.project.oldWorldImageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          env:
            - name: PLATFORM
              value: {{ include "microservice.cloud.provider" . }}
            - name: APP_NAME
              value: {{ .Values.application.name | lower | quote }}
            {{- if eq (include "microservice.cloud.provider" .) "AWS" }}
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- end }}
            {{- range .Values.application.oldWorld.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ include "microservice.application.containerPort" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ include "microservice.application.containerPort" . }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: fpm-pool-config-volume
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: php-config-volume
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: shared-files
              mountPath: /var/www/html
            - name: tmp
              mountPath: /tmp
            - name: newrelic-log
              mountPath: /var/log/newrelic/

        - name: nginx
          image: {{ include "microservice.nginx.imageURL" . }}
          imagePullPolicy: {{  .Values.nginx.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          lifecycle:
            postStart:
              exec:
                command: ["sh"]
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.internalPort }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              port: {{ include "microservice.application.containerPort" . }}
              path: {{ .Values.nginx.livenessProbe.path }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: {{ include "microservice.application.containerPort" . }}
              path: {{ .Values.nginx.readinessProbe.path }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: shared-files
              mountPath: /var/www/html
            - name: tmp
              mountPath: /tmp

        - name: logs
          image: {{ include "microservice.logging.imageURL" . }}
          resources:
            {{- toYaml .Values.logging.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: PLATFORM
              value: {{ include "microservice.cloud.provider" . }}
            - name: DOCKER_IMAGE
              value: {{ include "microservice.project.imageURL" . }}
            - name: ENVIRONMENT
              value: {{ include "microservice.cloud.environment" . }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NEW_RELIC_LICENSE_KEY
              value: {{ .Values.newrelic.licenseKey }}
            - name: FLUENT_BIT_LOG_PATH
              value: {{ .Values.logging.logPath }}
            - name: FLUENT_BIT_PARSER_PATH
              value: {{ .Values.logging.parserPath }}
            - name: FLUENT_BIT_MULTILINE
              value: {{ .Values.logging.multiLine | quote }}
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html

      securityContext:
        fsGroup: 1000

      volumes:
        - name: fpm-pool-config-volume
          configMap:
            name: fpm-pool-configmap
        - name: php-config-volume
          configMap:
            name: php-configmap
        - name: nginx-config-volume
          configMap:
            name: nginx-configmap
        - name: shared-files
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: newrelic-log
          emptyDir: {}
{{- end }}
