{{- if eq .Values.application.name "event" }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservice.application.name" . }}-oldworld
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.deployment.hpa.maxReplicas }}
  minReplicas: {{ .Values.deployment.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "microservice.application.name" . }}-oldworld
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment.hpa.targetCPU }}
    - type: Resource
      resource:
        name: memory
        targetAverageValue: {{ include "microservice.hpa.targetMemory" . }}
{{- end }}