{{- if and (eq .Values.application.name "event") (eq .Values.application.oldWorld.enabled true) }}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: do-not-preserve-host-oldworld
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
route:
  preserve_host: false
upstream:
  host_header: {{ include "microservice.application.name" . }}-oldworld.{{ .Release.Namespace }}.svc
{{- end }}