{{- if eq .Values.application.name "event" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.application.name" . }}-oldworld
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "microservice.application.name" . }}-oldworld
    app.kubernetes.io/instance: {{ .Release.Name }}-oldworld
{{- end }}
