{{- if eq .Values.application.name "horizon" }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-forwarded-header-to-host-header
spec:
  workloadSelector:
    labels:
      {{- include "php.labels" . | nindent 6 }}
      app.kubernetes.io/name: {{ include "php.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: {{ .Values.nginx.service.internalPort }}
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                headers = request_handle:headers()
                request_handle:logWarn("envoy_on_request")
                host = headers:get("x-forwarded-host")
                request_handle:logWarn("envoy_on_request: " .. host)
                headers:replace("host", host)
              end
{{- end }}
