{{- if eq .Values.application.name "horizon" }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: ping-access-service-entry-new-world
spec:
  hosts:
  {{- if .Values.serviceEntry.ping.hosts }}
  {{- range .Values.serviceEntry.ping.hosts }}
    - {{ . }}
  {{- end }}
  {{- end }}
  location: MESH_INTERNAL
  ports:
    - number: 8080
      name: http
      protocol: HTTP
  resolution: STATIC
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ include "php.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: newworld
{{- end }}
