{{- if eq .Values.application.name "data-feed" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.application.name" . }}-task-scheduler
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microservice.application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- include "microservice.annotations" . | nindent 8 }}
        {{- include "microservice.vault.annotations" . | nindent 8 }}
      labels:
        {{- include "microservice.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ include "microservice.application.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if eq (include "microservice.cloud.provider" .) "Azure" }}
        {{- if eq .Values.azure.identity.enabled true }}
        aadpodidbinding: {{ .Values.azure.identity.name }}
        {{- end }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "microservice.application.name" . }}
      containers:
        - name: {{ include "microservice.application.name" . }}
          image: {{ include "microservice.project.imageURL" . }}
          imagePullPolicy: {{ .Values.application.image.pullPolicy }}
          args: [ "schedule" ]
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          env:
            - name: AWS_REGION
              value: {{ .Values.cloud.region }}
            {{- range .Values.deployment.env }}
            - name: "{{.name}}"
              value: "{{.value}}"
            {{- end}}
          ports:
            - name: http
              containerPort: {{ include "microservice.application.containerPort" . }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application.resources | nindent 12 }}
          volumeMounts:
            - name: fpm-pool-config-volume
              mountPath: /usr/local/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: php-config-volume
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: shared-files
              mountPath: /var/www/html
            - name: tmp
              mountPath: /tmp
            - name: newrelic-log
              mountPath: /var/log/newrelic/

        - name: logs
          image: {{ include "microservice.logging.imageURL" . }}
          resources:
            {{- toYaml .Values.logging.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 1001
          env:
            - name: PLATFORM
              value: {{ include "microservice.cloud.provider" . }}
            - name: DOCKER_IMAGE
              value: {{ include "microservice.project.imageURL" . }}
            - name: ENVIRONMENT
              value: {{ .Values.cloud.environment }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NEW_RELIC_LICENSE_KEY
              value: {{ .Values.newrelic.licenseKey }}
            - name: FLUENT_BIT_LOG_PATH
              value: {{ .Values.logging.logPath }}
            - name: FLUENT_BIT_PARSER_PATH
              value: {{ .Values.logging.parserPath }}
            - name: FLUENT_BIT_MULTILINE
              value: {{ .Values.logging.multiLine | quote }}
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html

      securityContext:
        fsGroup: 1000

      volumes:
        - name: fpm-pool-config-volume
          configMap:
            name: fpm-pool-configmap
        - name: php-config-volume
          configMap:
            name: php-configmap
        - name: shared-files
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: newrelic-log
          emptyDir: {}
{{- end }}