{{- if eq .Values.application.name "data-feed" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "microservice.application.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  host: {{ include "microservice.application.name" . }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 6379
        tls:
          mode: SIMPLE
{{- end -}}
