{{- if eq .Values.service.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "networking.application.name" . }}
  labels:
    {{- include "networking.labels" . | nindent 4 }}
  annotations:
    {{- include "networking.annotations" . | nindent 4 }}
    {{- if eq .Values.service.externalDNS.enabled true }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.externalDNS.host }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "networking.application.name" . }}
{{- end }}
