{{- if eq (include "networking.application.name" .) "horizon" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "networking.application.name" . }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
    {{ printf "- %s" .}}
  {{- end }}
  http:
    - name: default-behavior
      match:
        - uri:
            prefix: "/api"
      route:
        - destination:
            host: {{ include "networking.application.name" . }}
          headers:
            request:
              set:
                X-Forwarded-Proto: "https"
      retries:
        attempts: 1
        perTryTimeout: 10s
{{- end }}
