apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "microservice.application.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: [
              {{- if .Values.istio.principals }}
                {{- range .Values.istio.principals }}
                {{ . | quote }},
                {{- end }}
              {{- end }}
            ]
