{{ if eq .Values.cloud.platform "Azure" }}
{{ if eq .Values.azure.identity.enabled true }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: "{{ .Values.azure.identity.name}}-binding"
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  azureIdentity: {{ .Values.azure.identity.name }}
  selector: {{ .Values.azure.identity.name }}
{{ end }}
{{ end }}