{{- if and (ne .Values.application.name "data-feed") (eq .Values.destinationRule.enabled true) }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "microservice.application.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
spec:
  host: {{ include "microservice.application.name" . }}
  trafficPolicy:
    tls:
      mode: {{ .Values.istio.tls.mode }}
  {{ if .Values.istio.subsets -}}
  subsets:
    {{- range .Values.istio.subsets }}
    - name: {{ .name }}
      labels:
      {{- range .labels }}
        {{ .name }}: {{ .value }}
      {{- end }}
    {{- end }}
  {{- end -}}
{{- end -}}