{{- if eq .Values.ingress.v1.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "microservice.application.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
    konghq.com/strip-path: "true"
    configuration.konghq.com: do-not-preserve-host
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "microservice.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- if .Values.ingress.pathRouted }}
          - path: {{ .Values.ingress.pathRouted }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "microservice.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
          {{- if .Values.ingress.pathMasked }}
          - path: {{ .Values.ingress.pathMasked }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "microservice.application.name" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
{{- end }}