apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.application.name" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    {{- include "microservice.annotations" . | nindent 4 }}
    {{-  if eq .Values.cloud.platform "AWS" }}
    eks.amazonaws.com/role-arn: {{ .Values.aws.iam_role }}
    {{- end }}