name: Lint and Test Charts
on:
  push:
    branches-ignore:
      - master
      - gh-pages
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run helm lint (lint)
        shell: bash
        run:  |
          search_dir=./charts
          helm repo add --username ${{ secrets.ACTION_GITHUB_USERNAME }} --password ${{ secrets.ACTION_GITHUB_TOKEN }} delio \
            https://raw.githubusercontent.com/deliowales/helm-charts/gh-pages
          for chart in "$search_dir"/*
          do
            /usr/local/bin/helm lint $chart --values=$chart/values.yaml
          done
